version: '3'

services:

    app:
        build:
            context: .
        container_name: imfeelinglucky_app
        restart: unless-stopped
        environment:
            COMPOSER_MEMORY_LIMIT: -1
        volumes:
            - .:/var/www/html:rw
            - ./docker/config/nginx/default.conf:/etc/nginx/sites-available/default.conf
        ports:
            - "5005:80"

    db:
        image: mysql:8.0.29
        container_name: imfeelinglucky_mysql
        command:
            - --default-authentication-plugin=mysql_native_password
        expose:
            - 3306
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=imfeelinglucky
        volumes:
            - ./docker/db_data:/var/lib/mysql:rw
        restart: always

    phpmyadmin:
        image: phpmyadmin:5.2.0
        container_name: imfeelinglucky_phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "8000:80"
        restart: always

    adminer:
        image: adminer
        container_name: imfeelinglucky_adminer
        ports:
            - "8008:8080"
        environment:
            ADMINER_DEFAULT_SERVER: imfeelinglucky_mysql

    supervisor:
        image: polinux/supervisor:alpine
        container_name: imfeelinglucky_supervisor
        volumes:
            - .:/var/www/html:rw
            - ./docker/config/supervisor/supervisord.conf:/etc/supervisord.conf

